# Read Dataset

In [1]:
import pandas as pd
df_train = pd.read_csv('./Input/training_set.csv')
df_train.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,NaN,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y

# Drop ID column as it is Statistically Insignificant

In [2]:
df_train = df_train.drop(labels=['Loan_ID'],axis=1)

# Converting Credit History to object

In [3]:
crd_hst = []
for i in range(len(df_train)):
    if df_train['Credit_History'][i]==1:
        crd_hst.append('Yes')
    elif df_train['Credit_History'][i]==0:
        crd_hst.append('No')
    else:
        crd_hst.append(None)
df_train['Credit_History']=crd_hst

# Pycaret Setup

In [4]:
from pycaret.classification import setup, compare_models, pull
setup(df_train,target='Loan_Status')
setup_df = pull()

# Compare best models

In [5]:
best_model = compare_models()
compare_df = pull()